# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUOEACpTkBl9ivfieyBvhCYR-vOGJr62
"""

!pip install -q xgboost openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

# ORIGINAL DATA (FOR EDA ONLY)
eda_df = df.copy()

# MODEL DATA (FOR ML ONLY)
model_df = df.copy()

eda_df["Date"] = pd.to_datetime(eda_df["Year"].astype(str) + "-" + eda_df["Month"].astype(str))

monthly_revenue = eda_df.groupby("Date")["Revenue_NGN"].sum()

plt.figure()
plt.plot(monthly_revenue.index, monthly_revenue.values)
plt.title("Monthly Revenue Trend")
plt.xticks(rotation=45)
plt.grid()
plt.show()

category_sales = eda_df.groupby("Category")["Revenue_NGN"].sum()

plt.figure()
category_sales.plot(kind="bar")
plt.title("Revenue by Category")
plt.show()

city_sales = eda_df.groupby("City")["Revenue_NGN"].sum()

plt.figure()
city_sales.plot(kind="bar")
plt.title("Revenue by City")
plt.show()

payment_counts = eda_df["Payment_Method"].value_counts()

plt.figure()
payment_counts.plot(kind="pie", autopct="%1.1f%%")
plt.title("Payment Methods Distribution")
plt.ylabel("")
plt.show()

plt.figure()
plt.hist(eda_df["Units_Sold"], bins=20)
plt.title("Units Sold Distribution")
plt.show()

label_encoders = {}
categorical_cols = ["City", "Category", "Payment_Method"]

for col in categorical_cols:
    le = LabelEncoder()
    model_df[col] = le.fit_transform(model_df[col])
    label_encoders[col] = le

X = model_df.drop(["Revenue_NGN", "Order_ID"], axis=1)
y = model_df["Revenue_NGN"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_model = RandomForestRegressor(n_estimators=200, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)

xgb_model = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6)
xgb_model.fit(X_train_scaled, y_train)
xgb_pred = xgb_model.predict(X_test_scaled)

X_train_lstm = X_train_scaled.reshape(X_train_scaled.shape[0], X_train_scaled.shape[1], 1)
X_test_lstm = X_test_scaled.reshape(X_test_scaled.shape[0], X_test_scaled.shape[1], 1)

lstm_model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(X_train_lstm.shape[1], 1)),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(1)
])

lstm_model.compile(optimizer='adam', loss='mse')
lstm_model.fit(X_train_lstm, y_train, epochs=10, batch_size=32, verbose=0)

lstm_pred = lstm_model.predict(X_test_lstm).flatten()

def evaluate(name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    print("\n", name)
    print("MAE :", mae)
    print("MSE :", mse)
    print("RMSE:", rmse)
    print("R2  :", r2)

    return [name, mae, mse, rmse, r2]

rf_res = evaluate("Random Forest", y_test, rf_pred)
xgb_res = evaluate("XGBoost", y_test, xgb_pred)
lstm_res = evaluate("LSTM", y_test, lstm_pred)

results_df = pd.DataFrame([rf_res, xgb_res, lstm_res],
                          columns=["Model", "MAE", "MSE", "RMSE", "R2"])

print(results_df)

best_model_name = results_df.loc[results_df["R2"].idxmax(), "Model"]

print("BEST MODEL:", best_model_name)

if best_model_name == "Random Forest":
    best_model = rf_model
elif best_model_name == "XGBoost":
    best_model = xgb_model
else:
    best_model = lstm_model

# ============================================================
# FUTURE FORECASTING USING RANDOM FOREST
# ============================================================

best_model = rf_model

def future_forecast(periods):

    # Get latest row
    latest_data = model_df.iloc[-1:].copy()

    forecasts = []

    for i in range(periods):

        # Increment month
        latest_data["Month"] += 1

        # Handle year rollover
        if latest_data["Month"].values[0] > 12:
            latest_data["Month"] = 1
            latest_data["Year"] += 1

        # Prepare features
        input_data = latest_data.drop(
            ["Revenue_NGN", "Order_ID"],
            axis=1
        )

        # Scale features
        scaled_data = scaler.transform(input_data)

        # Predict revenue
        prediction = best_model.predict(scaled_data)[0]

        # Save prediction
        forecasts.append(prediction)

        # Update revenue for next iteration
        latest_data["Revenue_NGN"] = prediction

    return forecasts

forecast_7 = future_forecast(7)
forecast_30 = future_forecast(30)
forecast_90 = future_forecast(90)

print("\n7-PERIOD FORECAST")
print(forecast_7)

print("\n30-PERIOD FORECAST")
print(forecast_30)

print("\n90-PERIOD FORECAST")
print(forecast_90)

plt.figure(figsize=(14,6))

plt.plot(forecast_7, label="7 Future Periods")
plt.plot(forecast_30, label="30 Future Periods")
plt.plot(forecast_90, label="90 Future Periods")

plt.title("Revenue Forecast Using Random Forest")
plt.xlabel("Future Period")
plt.ylabel("Predicted Revenue")

plt.legend()
plt.grid()

plt.show()

os.makedirs("/content/models", exist_ok=True)

pickle.dump(rf_model, open("/content/models/rf.pkl", "wb"))
pickle.dump(xgb_model, open("/content/models/xgb.pkl", "wb"))
pickle.dump(scaler, open("/content/models/scaler.pkl", "wb"))
pickle.dump(label_encoders, open("/content/models/encoders.pkl", "wb"))

lstm_model.save("/content/models/lstm.h5")